<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Bundle\ViewModel\ValidateQuantity;
?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */ ?>
<?php $_option      = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>

<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php
/** @var ValidateQuantity $viewModel */
$viewModel = $block->getData('validateQuantityViewModel');

/** @var OptionProductInfo $optionProductInfoViewModel */
$optionProductInfoViewModel = $block->getData('optionProductInfoViewModel');

$heatsinkCondition = $block->getProduct()->getHeatsinkCondition();
$heatsinkCondition = $optionProductInfoViewModel->getUnserializedHeatsinkConditionData($heatsinkCondition, $_option->getId());

?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label" for="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>">
        <span><?= $escaper->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
            <input type="hidden"
                   class="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>  product bundle option"
                   name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                   value="<?= $escaper->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
        <?php else:?>
            
            <?php foreach ($_selections as $_selection): ?>
                <div id="option-tier-prices-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>" 
                    <?php if ($_selection->getData('heatsink_performance')): ?>
                    data-heatsink-performance="<?= $escaper->escapeHtmlAttr($_selection->getData('heatsink_performance'))?>"
                    <?php endif; ?>
                    data-option-id="<?= $escaper->escapeHtmlAttr($_option->getId()) ?>"
                    class="option-tier-prices bundle-options options-<?= $escaper->escapeHtmlAttr($_option->getId()) ?> options-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?> <?= $_defaultQty && !$block->isSelected($_selection) ? ' disabled': '' ?> <?php if (!$_selection->isSaleable()) { echo ' disabled'; } ?>">
                    
                        <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection, false) ?>
                        <div data-role="selection-tier-prices"
                            data-selection-id="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                            class="selection-tier-prices">
                            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                            
                        </div>
                        <?php if ($_selection->isSaleable()): ?>
                            <select class="bundle-option-qty"
                                    name="<?=/* @noEscape */ 'bundle_option_['. $escaper->escapeHtmlAttr($_option->getId())?>]" 
                                    id="bundle-option-qty-<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                                    data-selection-id="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                                    data-option-id="<?= $escaper->escapeHtmlAttr($_option->getId()) ?>"
                                    <?php if ($heatsinkCondition): ?>
                                    data-heatsink-condition="<?= $escaper->escapeHtmlAttr($heatsinkCondition) ?>"
                                    <?php endif; ?>
                                    data-option-info="<?= $escaper->escapeHtmlAttr($optionProductInfoViewModel->getProductInfo($_selection, $_option)); ?>"
                                    >
                                <?php for ($i = 0; $i <= 10; $i++): ?>
                                    <option value="<?= $i ?>" 
                                        <?= $_defaultQty == $i && $block->isSelected($_selection) ? 'selected' : '' ?>>
                                        <?= $i ?>
                                    </option>
                                <?php endfor; ?>
                            </select>
                        <?php endif; ?>  
                </div>
            <?php endforeach; ?>
            <select id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                    data-selector="bundle_option[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                    
                    class="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?> product bundle option bundle-option-select hide-block change-container-classname"
                    
                <?php if ($_option->getRequired()) { echo 'data-validate = {required:true}'; } ?>>
                <option value=""><?= $escaper->escapeHtml(__('Choose a selection...')) ?></option>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                        <?php if ($block->isSelected($_selection)) { echo ' selected="selected"'; } ?>
                        <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>>
                        <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
        <div class="nested hide-block">
            <input <?php if (!$_canChangeQty) { echo ' disabled="disabled"'; } ?>
                    id="bundle-option-<?= $escaper->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                    class="input-text qty<?php if (!$_canChangeQty) { echo ' qty-disabled'; } ?>"
                    type="number"
                    min="0"
                    data-validate="<?= $escaper->escapeHtmlAttr($viewModel->getQuantityValidators()) ?>"
                    name="bundle_option_qty[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                    data-selector="bundle_option_qty[<?= $escaper->escapeHtmlAttr($_option->getId()) ?>]"
                    value="<?= $escaper->escapeHtmlAttr($_defaultQty) ?>"/>
        </div>
    </div>
</div>

